Document: yandex-libdispatch0
Title: Debian yandex-libdispatch0 Manual
Author: <insert document author here>
Abstract: This manual describes what yandex-libdispatch0 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yandex-libdispatch0/yandex-libdispatch0.sgml.gz

Format: postscript
Files: /usr/share/doc/yandex-libdispatch0/yandex-libdispatch0.ps.gz

Format: text
Files: /usr/share/doc/yandex-libdispatch0/yandex-libdispatch0.text.gz

Format: HTML
Index: /usr/share/doc/yandex-libdispatch0/html/index.html
Files: /usr/share/doc/yandex-libdispatch0/html/*.html
